name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Create dummy data.json
        run: echo '{"pages":[]}' >> apps/blog/data.json
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: apps/blog
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
