name: Full deploy

on: [repository_dispatch, workflow_dispatch]

jobs:
  build-and-deploy-cms:
    if: ${{ github.event.action == 'full-release' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: yarn install --immutable --immutable-cache
      - run: yarn cms build
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DOKKU_DEPLOY_KEY }}
      - run: echo '167.71.190.115 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEYg+BGxM8IdEoQ8fx7aDoclC0eNXSpI6l/QkLRMF/cvjJcSCk4kz/4LEkSU8eXFawp8IX/yNOyV11sJZtCVBCs=' >> ~/.ssh/known_hosts
      - run: |
          git config --global user.email "deploy-bot@ertrzyiks.me"
          git config --global user.name "Deploy Bot"
          git remote add dokku dokku@167.71.190.115:yummy-api
          git add .
          git add --force apps/cms/build
          git commit -m 'Update'
          git push dokku master --force

  build-blog:
    runs-on: ubuntu-latest
    needs: [build-and-deploy-cms]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: yarn install --immutable --immutable-cache
      - name: Build project
        run: for i in {1..3}; do yarn workspace blog build:prod && break; done
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          API_URL: https://api.kuchnia-yummy.pl
          API_USER_EMAIL: bot@ertrzyiks.me
          API_USER_PASSWORD: ${{ secrets.STRAPI_BOT_USER_PASSWORD }}
      - uses: actions/upload-artifact@v2
        with:
          name: public
          path: apps/blog/public/

  deploy-blog:
    runs-on: ubuntu-latest
    needs: [build-blog]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: public
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DOKKU_DEPLOY_KEY }}
      - run: echo '167.71.190.115 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEYg+BGxM8IdEoQ8fx7aDoclC0eNXSpI6l/QkLRMF/cvjJcSCk4kz/4LEkSU8eXFawp8IX/yNOyV11sJZtCVBCs=' >> ~/.ssh/known_hosts
      - run: |
          git config --global user.email "deploy-bot@ertrzyiks.me"
          git config --global user.name "Deploy Bot"
          git init
          git remote add dokku dokku@167.71.190.115:yummy
          git add .
          git commit -m 'Update'
          git push dokku master --force
