name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install --frozen-lockfile
      - run: yarn lerna run --scope @yummy/core lint
      - name: Run tests
        run: yarn lerna run --scope @yummy/core test
        env:
          CI: true
      - name: Run tests
        run: yarn lerna run --scope @yummy/core build
        env:
          GATSBY_SOURCE: test
