name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install --frozen-lockfile
      - run: yarn lerna run --scope @yummy/core lint
      - name: Run tests
        run: yarn lerna run --scope @yummy/core test
        env:
          CI: true
      - name: Build project
        run: yarn lerna run --scope @yummy/core build
        env:
          GATSBY_SOURCE: test

  deploy-kuchnia-yummy-pl:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
        with:
          path: app
      - uses: actions/checkout@v2
        with:
          repository: ertrzyiks/yummy-content
          path: yummy-content
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install --frozen-lockfile
        working-directory: app
      - name: Build project
        run: for i in {1..3}; do yarn lerna run --scope @yummy/core build && break; done
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        working-directory: app
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DOKKU_DEPLOY_KEY }}
      - run: echo 'ertrzyiks.me,104.236.224.189 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNfW9tfAr21CQlapt944WeYOaSftTQB3Ly/Tm/1ZeXYEI08w9v9FEXRG2E+Sj/EDHimklHLlCwWCPMqMYFMQsMg=' >> ~/.ssh/known_hosts
      - run: |
          git config --global user.email "deploy-bot@ertrzyiks.me"
          git config --global user.name "Deploy Bot"
          git init
          git remote add dokku dokku@ertrzyiks.me:yummy
          git add .
          git commit -m 'Update'
          git push dokku master --force
        working-directory: app/packages/core/public
