name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn lerna run --scope @yummy/core lint
      - name: Run tests
        run: yarn lerna run --scope @yummy/core test
        env:
          CI: true
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - name: Run e2e tests
        run: yarn lerna run --stream --scope @yummy/core test:e2e:ci
        env:
          GATSBY_SOURCE: test
      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: visual
          path: packages/core/cypress/screenshots

  visual:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - name: Run visual tests
        run: yarn lerna run --stream --scope @yummy/core test:visual
      - name: Upload visual comparison results
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: visual
          path: packages/core/puppeteer/screenshots

  tag-latest:
    runs-on: ubuntu-latest
    needs: [build, visual, e2e]
    steps:
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.MY_GITHUB_TOKEN}}
          script: |
            await github.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/latest',
              sha: context.sha,
              force: true
            })

  deploy-kuchnia-yummy-pl:
    runs-on: ubuntu-latest
    needs: [tag-latest]

    steps:
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.MY_GITHUB_TOKEN}}
          script: |
            github.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: 'yummy-content',
              event_type: 'deploy'
            })
  deploy-mini-kuchnia-yummy-pl:
    runs-on: ubuntu-latest
    needs: [tag-latest]

    steps:
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.MY_GITHUB_TOKEN}}
          script: |
            github.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: 'mini-yummy-content',
              event_type: 'deploy'
            })
