name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn lerna run --scope @yummy/core lint
      - name: Run tests
        run: yarn lerna run --scope @yummy/core test
        env:
          CI: true
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - name: Run e2e tests
        run: yarn lerna run --stream --scope @yummy/core test:e2e:ci
        env:
          GATSBY_SOURCE: test
      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: visual
          path: packages/core/cypress/screenshots

  visual:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - name: Run visual tests
        run: yarn lerna run --stream --scope @yummy/core test:visual
      - name: Upload visual comparison results
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: visual
          path: packages/core/puppeteer/screenshots

  deploy-kuchnia-yummy-pl:
    runs-on: ubuntu-latest
    needs: [build, visual, e2e]
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
        with:
          path: app
      - uses: actions/checkout@v2
        with:
          repository: yummy-recipes/yummy-content
          path: yummy-content
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
        working-directory: app
      - name: Build project
        run: for i in {1..3}; do yarn lerna run --scope @yummy/core build && break; done
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        working-directory: app
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DOKKU_DEPLOY_KEY }}
      - run: echo 'ertrzyiks.me,104.236.224.189 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNfW9tfAr21CQlapt944WeYOaSftTQB3Ly/Tm/1ZeXYEI08w9v9FEXRG2E+Sj/EDHimklHLlCwWCPMqMYFMQsMg=' >> ~/.ssh/known_hosts
      - run: |
          git config --global user.email "deploy-bot@ertrzyiks.me"
          git config --global user.name "Deploy Bot"
          git init
          git remote add dokku dokku@ertrzyiks.me:yummy
          git add .
          git commit -m 'Update'
          git push dokku master --force
        working-directory: app/packages/core/public

  deploy-mini-kuchnia-yummy-pl:
    runs-on: ubuntu-latest
    needs: [build, visual, e2e, deploy-kuchnia-yummy-pl]
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
        with:
          path: app
      - uses: actions/checkout@v2
        with:
          repository: yummy-recipes/mini-yummy-content
          path: mini-yummy-content
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
        working-directory: app
      - name: Build project
        run: for i in {1..3}; do yarn minibuild && break; done
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        working-directory: app
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DOKKU_DEPLOY_KEY }}
      - run: echo 'ertrzyiks.me,104.236.224.189 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNfW9tfAr21CQlapt944WeYOaSftTQB3Ly/Tm/1ZeXYEI08w9v9FEXRG2E+Sj/EDHimklHLlCwWCPMqMYFMQsMg=' >> ~/.ssh/known_hosts
      - run: |
          git config --global user.email "deploy-bot@ertrzyiks.me"
          git config --global user.name "Deploy Bot"
          git init
          git remote add dokku dokku@ertrzyiks.me:mini-yummy
          git add .
          git commit -m 'Update'
          git push dokku master --force
        working-directory: app/packages/core/public
