name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - run: yarn install --immutable --immutable-cache
      - run: yarn test:ci

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install --immutable --immutable-cache
      - run: yarn test:e2e:ci
      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress
          path: apps/blog/cypress/screenshots

  visual:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn install --immutable --immutable-cache
      - run: yarn test:visual:ci
      - name: Upload visual comparison results
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: visual
          path: apps/blog/puppeteer/screenshots

  deploy:
    runs-on: ubuntu-latest
    needs: [test, visual, e2e]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          event-type: full-release
