name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js test

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js test:e2e:ci --only e2e -v
      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress
          path: apps/blog/cypress/screenshots

  visual:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js test:visual --only e2e -v
      - name: Upload visual comparison results
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: visual
          path: apps/blog/puppeteer/screenshots

  deploy:
    runs-on: ubuntu-latest
    needs: [test, visual, e2e]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: yummy-recipes/yummy
          event-type: deploy
