name: CI

on: [push]

jobs:
  css-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: find apps/blog -type f -name "*.module.css" | node scripts/tailwind-progress.js >> $GITHUB_STEP_SUMMARY

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - run: yarn install --immutable --immutable-cache
      - run: yarn test:ci

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn install --immutable --immutable-cache
      - run: yarn test:e2e:ci
      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress
          path: apps/blog/cypress/screenshots

  deploy:
    runs-on: ubuntu-latest
    needs: [test, e2e]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          event-type: full_release
